/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.star.wars.demo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StarWarsCharacter service. Represents a row in the &quot;StarWarsCharacter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.star.wars.demo.model.impl.StarWarsCharacterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.star.wars.demo.model.impl.StarWarsCharacterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StarWarsCharacter
 * @see com.liferay.star.wars.demo.model.impl.StarWarsCharacterImpl
 * @see com.liferay.star.wars.demo.model.impl.StarWarsCharacterModelImpl
 * @generated
 */
@ProviderType
public interface StarWarsCharacterModel extends BaseModel<StarWarsCharacter>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a star wars character model instance should use the {@link StarWarsCharacter} interface instead.
	 */

	/**
	 * Returns the primary key of this star wars character.
	 *
	 * @return the primary key of this star wars character
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this star wars character.
	 *
	 * @param primaryKey the primary key of this star wars character
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the star wars character ID of this star wars character.
	 *
	 * @return the star wars character ID of this star wars character
	 */
	public long getStarWarsCharacterId();

	/**
	 * Sets the star wars character ID of this star wars character.
	 *
	 * @param starWarsCharacterId the star wars character ID of this star wars character
	 */
	public void setStarWarsCharacterId(long starWarsCharacterId);

	/**
	 * Returns the group ID of this star wars character.
	 *
	 * @return the group ID of this star wars character
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this star wars character.
	 *
	 * @param groupId the group ID of this star wars character
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this star wars character.
	 *
	 * @return the company ID of this star wars character
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this star wars character.
	 *
	 * @param companyId the company ID of this star wars character
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this star wars character.
	 *
	 * @return the user ID of this star wars character
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this star wars character.
	 *
	 * @param userId the user ID of this star wars character
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this star wars character.
	 *
	 * @return the user uuid of this star wars character
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this star wars character.
	 *
	 * @param userUuid the user uuid of this star wars character
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this star wars character.
	 *
	 * @return the user name of this star wars character
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this star wars character.
	 *
	 * @param userName the user name of this star wars character
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this star wars character.
	 *
	 * @return the create date of this star wars character
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this star wars character.
	 *
	 * @param createDate the create date of this star wars character
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this star wars character.
	 *
	 * @return the modified date of this star wars character
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this star wars character.
	 *
	 * @param modifiedDate the modified date of this star wars character
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this star wars character.
	 *
	 * @return the name of this star wars character
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this star wars character.
	 *
	 * @param name the name of this star wars character
	 */
	public void setName(String name);

	/**
	 * Returns the picture of this star wars character.
	 *
	 * @return the picture of this star wars character
	 */
	@AutoEscape
	public String getPicture();

	/**
	 * Sets the picture of this star wars character.
	 *
	 * @param picture the picture of this star wars character
	 */
	public void setPicture(String picture);

	/**
	 * Returns the fraction of this star wars character.
	 *
	 * @return the fraction of this star wars character
	 */
	@AutoEscape
	public String getFraction();

	/**
	 * Sets the fraction of this star wars character.
	 *
	 * @param fraction the fraction of this star wars character
	 */
	public void setFraction(String fraction);

	/**
	 * Returns the description of this star wars character.
	 *
	 * @return the description of this star wars character
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this star wars character.
	 *
	 * @param description the description of this star wars character
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StarWarsCharacter starWarsCharacter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StarWarsCharacter> toCacheModel();

	@Override
	public StarWarsCharacter toEscapedModel();

	@Override
	public StarWarsCharacter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}